version: "3.5"
services:
  syslog:
    image: jhaoheng/remote_syslog2:v0.2
    container_name: papertrail
    volumes:
      - ./config.yml:/home/papertrail/config.yml
      - ./fakeLog:/var/log/fakeLog
    command: sh -c "remote_syslog -D -c /home/papertrail/config.yml"